---
title: "EBOLA_ODEs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This R Markdown document models the Seasonal Spillover of Ebola Virus using a system of coupled ordinary differential equations (ODEs).

```{r Load package, include=FALSE}
library(deSolve)
```
########################
# Two Pacth EBOLA ODEs #
########################
```{r ODEs, echo=FALSE}
####################################
# Disease Transmission Rate by (t) #
####################################
#P=1

beta_A<-function(time){
  return(60*(1+(0.5*cos(((2*pi*time)/1))))) # Correct.
}

beta_B<-function(time){
  
  return(5*(1+(0.5*cos((2*pi*time)/1)))) # Correct.
         }
##########################
# Disease Dispersal Rate #  
##########################

phi_AB<-function(time){
  return(0.4*(1 + 0.5*cos((2*pi*time/1)))) # Correct.
}

phi_BA<-function(time){
  
  return(0.04*(1 + 0.5*(cos((2*pi*time)/1)))) # Correct.
         }
#--------------------------------------------------------------------#
two_patch_SIR <- function(time, variables, parameters, phi_BA, phi_AB, beta_A, beta_B) {
  with(as.list(c(variables, parameters)), {
    
    dS_A <- (mu_A * N_A) - ((beta_A(time))*(I_A/N_A)*(S_A)) - (mu_A + phi_AB(time)*S_A) + (phi_BA(time)*S_B) # Correct.
    
    dI_A <- (beta_A(time)*(I_A/N_A)*S_A) - ((mu_A + gamma_A + phi_AB(time)) * I_A) + (phi_BA(time)*I_B) # Correct.
    
    dR_A <- (gamma_A*I_A)-((mu_A + phi_AB(time))*R_A) + (phi_BA(time)*R_B)  # Correct.
    
#-------------------------------------------------------------------#
    
    dS_B <-(mu_B * N_B) - ((beta_B(time))*(I_B/N_B)*(S_B)) - (mu_B + phi_BA(time)*S_B) + (phi_AB(time)*S_A) # Correct.
    
    dI_B <-(beta_B(time)*(I_B/N_B)*S_B) - ((mu_B + gamma_B + phi_BA(time)*I_B)) + (phi_AB(time)*I_A) # Correct.
    
    dR_B <-(gamma_B*I_B)-((mu_B + phi_BA(time))*R_B) + (phi_AB(time)*R_A) # Correct.
    
    return(list(c(dS_A, dI_A, dR_A, dS_B, dI_B, dR_B)))
  })
}

# Set up initial values for the variables
initial_values <- c(
  S_A = 95, I_A = 5, R_A = 0,   # Initial values for patch A
  S_B = 995, I_B = 5, R_B = 0   # Initial values for patch B
)

# Define parameters for the system
parameters_values <- list(
  N_A = 100,
  N_B = 1000,
  mu_A = 0.06,
  mu_B = 0.02,
  gamma_A = 12,
  gamma_B = 12,
  phi_BA = phi_BA,
  phi_AB = phi_AB,
  beta_A = beta_A,
  beta_B = beta_B
)

# Define a sequence of time points
time <- seq(0, 1, by = 0.05)

# Solve the system of differential equations
sir_values <- ode(
  y = initial_values,
  times = time,
  func = two_patch_SIR,
  parms = parameters_values
)

# Print the solution
print(sir_values)
```

################################################################
# To make the same graph I need to adapt according to FIGURE 5 #
################################################################

```{r ODEs, echo=FALSE}
#################################################
#            Transform to Data Frame            #
#################################################

sir_values <- as.data.frame(sir_values)
sir_values

######################################
#            PLOT PATCH A            #
######################################
with(sir_values, {
# plotting the time series of susceptibles:
  plot(time, S_A, type = "l", col = "blue",
       xlab = "time", ylab = "number of people", ylim = c(0, 100))
# adding the time series of infectious:
  lines(time, I_A, col = "red")
# adding the time series of recovered:
  lines(time, R_A, col = "green")
})

# adding a legend:
legend("right", c("susceptibles", "infectious", "recovered"),
       col = c("blue", "red", "green"), lty = 1, bty = "n")

#####################################
#            PLOT PATCH B           #
#####################################
with(sir_values, {
# plotting the time series of susceptibles:
  plot(time, S_B, type = "l", col = "blue",
       xlab = "time", ylab = "number of people", ylim = c(0, 1000))
# adding the time series of infectious:
  lines(time, I_B, col = "red")
# adding the time series of recovered:
  lines(time, R_B, col = "green")
})

# adding a legend:
legend("right", c("susceptibles", "infectious", "recovered"),
       col = c("blue", "red", "green"), lty = 1, bty = "n")

```

